### ISSUE TITLE
only 2 files present

### ISSUE THREAD

**Issue by Ripcord227** [baum1810/fixed-token-grabber#3]
When I open it there is only the README and the py file but when I try and open it, it immediately closes and doesn't do anything. I am on python 3.10

**Comment by baum1810** [comment]
Hello, and yeah there are only 2 files and you just need one of them and that is the batch file and also you dont need python installed or something because batch is on the most windows pcs preinstalled also it isnt a builder so you need to rightclick on the batch file and then click on edit and replace the text YOURWEBHOOK with your webhook and then as soon as u open it your data should get sended to your webhook
